name: qartvm
description: qartvm (pronounced 'kar-toom') is a Quantum Computing Simulation package for Dart & Flutter
version: 0.0.5
repository: https://github.com/d-markey/qartvm

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies: 
  squadron:
  antlr4: ^4.12.0

dev_dependencies:
  lints: 
  test: 
  squadron_builder:
  build_runner:
