name: qartvm
description: qartvm (pronounced 'kar-toom') is a Quantum Computing Simulation package for Dart & Flutter
version: 0.0.5
repository: https://github.com/d-markey/qartvm

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  squadron: ^4.3.3

dev_dependencies:
  lints: ^1.0.1
  test: ^1.22.2
